apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
data:
  index.html: |
    <html>
    <head><title>Dev Environment</title></head>
    <body>
    <h1>Welcome to the Dev Environment</h1>
    </body>
    </html>
