apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: ['sh', '-c', 'cp /config/index.html /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: nginx-config
          mountPath: /config
        - name: html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: html
        emptyDir: {}